/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Back3 model module.
 * @module model/Back3
 * @version 1.0.0
 */
export class Back3 {
  /**
   * Constructs a new <code>Back3</code>.
   * The content of the back of this item
   * @alias module:model/Back3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Back3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Back3} obj Optional instance to populate.
   * @return {module:model/Back3} The populated <code>Back3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Back3();
      if (data.hasOwnProperty('orientation'))
        obj.orientation = ApiClient.convertToType(data['orientation'], 'Number');
      if (data.hasOwnProperty('page_number'))
        obj.pageNumber = ApiClient.convertToType(data['page_number'], 'Number');
      if (data.hasOwnProperty('reference'))
        obj.reference = ApiClient.convertToType(data['reference'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>orientation</code> property.
 * @enum {Number}
 * @readonly
 */
Back3.OrientationEnum = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 90
   * @const
   */
  _90: 90,

  /**
   * value: 180
   * @const
   */
  _180: 180,

  /**
   * value: 270
   * @const
   */
  _270: 270
};
/**
 * @member {module:model/Back3.OrientationEnum} orientation
 */
Back3.prototype.orientation = undefined;

/**
 * @member {Number} pageNumber
 */
Back3.prototype.pageNumber = undefined;

/**
 * @member {String} reference
 */
Back3.prototype.reference = undefined;

