/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BatchMemberCreate model module.
 * @module model/BatchMemberCreate
 * @version 1.0.0
 */
export class BatchMemberCreate {
  /**
   * Constructs a new <code>BatchMemberCreate</code>.
   * A BatchMember represents the status of a Signature within a Batch.
   * @alias module:model/BatchMemberCreate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BatchMemberCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BatchMemberCreate} obj Optional instance to populate.
   * @return {module:model/BatchMemberCreate} The populated <code>BatchMemberCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BatchMemberCreate();
      if (data.hasOwnProperty('batch_id'))
        obj.batchId = ApiClient.convertToType(data['batch_id'], 'String');
      if (data.hasOwnProperty('signature_id'))
        obj.signatureId = ApiClient.convertToType(data['signature_id'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} batchId
 */
BatchMemberCreate.prototype.batchId = undefined;

/**
 * @member {String} signatureId
 */
BatchMemberCreate.prototype.signatureId = undefined;

/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
BatchMemberCreate.StateEnum = {
  /**
   * value: "pending"
   * @const
   */
  pending: "pending",

  /**
   * value: "included"
   * @const
   */
  included: "included",

  /**
   * value: "excluded"
   * @const
   */
  excluded: "excluded"
};
/**
 * Some signatures that have been added to batches can be rejected by planning software due to a number of reasons - incompatible substrates,
 * @member {module:model/BatchMemberCreate.StateEnum} state
 */
BatchMemberCreate.prototype.state = undefined;

