/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Back1} from './Back1';
import {Dimensions1} from './Dimensions1';
import {Front1} from './Front1';
import {Position1} from './Position1';

/**
 * The BoxModelFinishingUpdate model module.
 * @module model/BoxModelFinishingUpdate
 * @version 1.0.0
 */
export class BoxModelFinishingUpdate {
  /**
   * Constructs a new <code>BoxModelFinishingUpdate</code>.
   * @alias module:model/BoxModelFinishingUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BoxModelFinishingUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoxModelFinishingUpdate} obj Optional instance to populate.
   * @return {module:model/BoxModelFinishingUpdate} The populated <code>BoxModelFinishingUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BoxModelFinishingUpdate();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('dimensions'))
        obj.dimensions = Dimensions1.constructFromObject(data['dimensions']);
      if (data.hasOwnProperty('position'))
        obj.position = Position1.constructFromObject(data['position']);
      if (data.hasOwnProperty('front'))
        obj.front = Front1.constructFromObject(data['front']);
      if (data.hasOwnProperty('back'))
        obj.back = Back1.constructFromObject(data['back']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BoxModelFinishingUpdate.prototype.id = undefined;

/**
 * Allowed values for the <code>kind</code> property.
 * @enum {String}
 * @readonly
 */
BoxModelFinishingUpdate.KindEnum = {
  /**
   * value: "finishing"
   * @const
   */
  finishing: "finishing"
};
/**
 * @member {module:model/BoxModelFinishingUpdate.KindEnum} kind
 */
BoxModelFinishingUpdate.prototype.kind = undefined;

/**
 * @member {module:model/Dimensions1} dimensions
 */
BoxModelFinishingUpdate.prototype.dimensions = undefined;

/**
 * @member {module:model/Position1} position
 */
BoxModelFinishingUpdate.prototype.position = undefined;

/**
 * @member {module:model/Front1} front
 */
BoxModelFinishingUpdate.prototype.front = undefined;

/**
 * @member {module:model/Back1} back
 */
BoxModelFinishingUpdate.prototype.back = undefined;

// Implement BoxModelIntermediateLayoutChildrenUpdate interface:
// Implement BoxModelPageChildrenUpdate interface:
// Implement BoxModelPartLayoutChildrenUpdate interface:
// Implement BoxModelRollSegmentChildrenUpdate interface:
// Implement BoxModelSheetChildrenUpdate interface:
// Implement BoxModelSpreadChildrenUpdate interface:
