/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Bleeds3} from './Bleeds3';
import {BoxModelPageChildrenUpdate} from './BoxModelPageChildrenUpdate';
import {Dimensions1} from './Dimensions1';
import {Front3} from './Front3';
import {Position1} from './Position1';
import {PrintFreeMargins3} from './PrintFreeMargins3';
import {Rear1} from './Rear1';

/**
 * The BoxModelPageUpdate model module.
 * @module model/BoxModelPageUpdate
 * @version 1.0.0
 */
export class BoxModelPageUpdate {
  /**
   * Constructs a new <code>BoxModelPageUpdate</code>.
   * @alias module:model/BoxModelPageUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>BoxModelPageUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoxModelPageUpdate} obj Optional instance to populate.
   * @return {module:model/BoxModelPageUpdate} The populated <code>BoxModelPageUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BoxModelPageUpdate();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('sides'))
        obj.sides = ApiClient.convertToType(data['sides'], 'String');
      if (data.hasOwnProperty('dimensions'))
        obj.dimensions = Dimensions1.constructFromObject(data['dimensions']);
      if (data.hasOwnProperty('position'))
        obj.position = Position1.constructFromObject(data['position']);
      if (data.hasOwnProperty('front'))
        obj.front = Front3.constructFromObject(data['front']);
      if (data.hasOwnProperty('rear'))
        obj.rear = Rear1.constructFromObject(data['rear']);
      if (data.hasOwnProperty('bleeds'))
        obj.bleeds = Bleeds3.constructFromObject(data['bleeds']);
      if (data.hasOwnProperty('print_free_margins'))
        obj.printFreeMargins = PrintFreeMargins3.constructFromObject(data['print_free_margins']);
      if (data.hasOwnProperty('children'))
        obj.children = ApiClient.convertToType(data['children'], [BoxModelPageChildrenUpdate]);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
BoxModelPageUpdate.prototype.id = undefined;

/**
 * Allowed values for the <code>kind</code> property.
 * @enum {String}
 * @readonly
 */
BoxModelPageUpdate.KindEnum = {
  /**
   * value: "page"
   * @const
   */
  page: "page"
};
/**
 * @member {module:model/BoxModelPageUpdate.KindEnum} kind
 */
BoxModelPageUpdate.prototype.kind = undefined;

/**
 * Allowed values for the <code>sides</code> property.
 * @enum {String}
 * @readonly
 */
BoxModelPageUpdate.SidesEnum = {
  /**
   * value: "one"
   * @const
   */
  one: "one",

  /**
   * value: "headtohead"
   * @const
   */
  headtohead: "headtohead",

  /**
   * value: "headtofoot"
   * @const
   */
  headtofoot: "headtofoot"
};
/**
 * @member {module:model/BoxModelPageUpdate.SidesEnum} sides
 */
BoxModelPageUpdate.prototype.sides = undefined;

/**
 * @member {module:model/Dimensions1} dimensions
 */
BoxModelPageUpdate.prototype.dimensions = undefined;

/**
 * @member {module:model/Position1} position
 */
BoxModelPageUpdate.prototype.position = undefined;

/**
 * @member {module:model/Front3} front
 */
BoxModelPageUpdate.prototype.front = undefined;

/**
 * @member {module:model/Rear1} rear
 */
BoxModelPageUpdate.prototype.rear = undefined;

/**
 * @member {module:model/Bleeds3} bleeds
 */
BoxModelPageUpdate.prototype.bleeds = undefined;

/**
 * @member {module:model/PrintFreeMargins3} printFreeMargins
 */
BoxModelPageUpdate.prototype.printFreeMargins = undefined;

/**
 * @member {Array.<module:model/BoxModelPageChildrenUpdate>} children
 */
BoxModelPageUpdate.prototype.children = undefined;

// Implement BoxModelIntermediateLayoutChildrenUpdate interface:
// Implement BoxModelPartLayoutChildrenUpdate interface:
// Implement BoxModelRollSegmentChildrenUpdate interface:
// Implement BoxModelSheetChildrenUpdate interface:
// Implement BoxModelSpreadChildrenUpdate interface:
