/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {IntermediateProduct} from './IntermediateProduct';
import {Workstep} from './Workstep';
import {WorkstepGroup} from './WorkstepGroup';

/**
 * The InlineResponse201 model module.
 * @module model/InlineResponse201
 * @version 1.0.0
 */
export class InlineResponse201 {
  /**
   * Constructs a new <code>InlineResponse201</code>.
   * @alias module:model/InlineResponse201
   * @class
   * @param workstepGroups {Array.<module:model/WorkstepGroup>} 
   * @param worksteps {Array.<module:model/Workstep>} 
   * @param intermediateProducts {Array.<module:model/IntermediateProduct>} 
   * @param finishedProduct {Object} 
   */
  constructor(workstepGroups, worksteps, intermediateProducts, finishedProduct) {
    this.workstepGroups = workstepGroups;
    this.worksteps = worksteps;
    this.intermediateProducts = intermediateProducts;
    this.finishedProduct = finishedProduct;
  }

  /**
   * Constructs a <code>InlineResponse201</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse201} obj Optional instance to populate.
   * @return {module:model/InlineResponse201} The populated <code>InlineResponse201</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse201();
      if (data.hasOwnProperty('workstep_groups'))
        obj.workstepGroups = ApiClient.convertToType(data['workstep_groups'], [WorkstepGroup]);
      if (data.hasOwnProperty('worksteps'))
        obj.worksteps = ApiClient.convertToType(data['worksteps'], [Workstep]);
      if (data.hasOwnProperty('intermediate_products'))
        obj.intermediateProducts = ApiClient.convertToType(data['intermediate_products'], [IntermediateProduct]);
      if (data.hasOwnProperty('finished_product'))
        obj.finishedProduct = ApiClient.convertToType(data['finished_product'], Object);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/WorkstepGroup>} workstepGroups
 */
InlineResponse201.prototype.workstepGroups = undefined;

/**
 * @member {Array.<module:model/Workstep>} worksteps
 */
InlineResponse201.prototype.worksteps = undefined;

/**
 * @member {Array.<module:model/IntermediateProduct>} intermediateProducts
 */
InlineResponse201.prototype.intermediateProducts = undefined;

/**
 * @member {Object} finishedProduct
 */
InlineResponse201.prototype.finishedProduct = undefined;

