/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BoxUpdate} from './BoxUpdate';

/**
 * The LayoutUpdate model module.
 * @module model/LayoutUpdate
 * @version 1.0.0
 */
export class LayoutUpdate {
  /**
   * Constructs a new <code>LayoutUpdate</code>.
   * @alias module:model/LayoutUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LayoutUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LayoutUpdate} obj Optional instance to populate.
   * @return {module:model/LayoutUpdate} The populated <code>LayoutUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LayoutUpdate();
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], [BoxUpdate]);
      if (data.hasOwnProperty('format'))
        obj.format = ApiClient.convertToType(data['format'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/BoxUpdate>} contents
 */
LayoutUpdate.prototype.contents = undefined;

/**
 * Allowed values for the <code>format</code> property.
 * @enum {String}
 * @readonly
 */
LayoutUpdate.FormatEnum = {
  /**
   * value: "box"
   * @const
   */
  box: "box"
};
/**
 * The format that is used for the layout description. Currently only the `box` format is supported, but in the future this will be extended with a path based format as well. Third party applications must support the `box` format, support of path based formats is optional, but required for everything packaging related.
 * @member {module:model/LayoutUpdate.FormatEnum} format
 */
LayoutUpdate.prototype.format = undefined;

/**
 * Allowed values for the <code>version</code> property.
 * @enum {String}
 * @readonly
 */
LayoutUpdate.VersionEnum = {
  /**
   * value: "1"
   * @const
   */
  _1: "1"
};
/**
 * The version of the layout description schema used here. Might be a numeric value or a string.
 * @member {module:model/LayoutUpdate.VersionEnum} version
 */
LayoutUpdate.prototype.version = undefined;

/**
 * Allowed values for the <code>unit</code> property.
 * @enum {String}
 * @readonly
 */
LayoutUpdate.UnitEnum = {
  /**
   * value: "mm"
   * @const
   */
  mm: "mm",

  /**
   * value: "cm"
   * @const
   */
  cm: "cm",

  /**
   * value: "pt"
   * @const
   */
  pt: "pt",

  /**
   * value: "pica"
   * @const
   */
  pica: "pica",

  /**
   * value: "pixel"
   * @const
   */
  pixel: "pixel",

  /**
   * value: "inch"
   * @const
   */
  inch: "inch"
};
/**
 * The unit of measurement used for all measures inside this layout
 * @member {module:model/LayoutUpdate.UnitEnum} unit
 */
LayoutUpdate.prototype.unit = undefined;

// Implement OneOfBatchSignatureUpdateLayout interface:
// Implement OneOfIntermediateProductUpdateLayout interface:
// Implement OneOfPartUpdateLayout interface:
// Implement OneOfSignatureUpdateLayout interface:
