/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Substrate model module.
 * @module model/Substrate
 * @version 1.0.0
 */
export class Substrate {
  /**
   * Constructs a new <code>Substrate</code>.
   * @alias module:model/Substrate
   * @class
   * @param id {String} 
   * @param createdAt {Date} 
   * @param updatedAt {Date} 
   * @param foo {String} TODO
   */
  constructor(id, createdAt, updatedAt, foo) {
    this.id = id;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
    this.foo = foo;
  }

  /**
   * Constructs a <code>Substrate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Substrate} obj Optional instance to populate.
   * @return {module:model/Substrate} The populated <code>Substrate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Substrate();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
      if (data.hasOwnProperty('foo'))
        obj.foo = ApiClient.convertToType(data['foo'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Substrate.prototype.id = undefined;

/**
 * @member {Date} createdAt
 */
Substrate.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
Substrate.prototype.updatedAt = undefined;

/**
 * TODO
 * @member {String} foo
 */
Substrate.prototype.foo = undefined;

// Implement OneOfImposingSubstrate interface:
