/*
 * Mission Control
 * This is the documentation of all API endpoints provided by Mission Control.  ## Provided OAuth Scopes - `mission_control.commissionings.r` [`Commissioning`]: Read information of all commissionings - `mission_control.commissionings.w` [`Commissioning`]: Create or update commissioning related models - `mission_control.estimates.r` [`Estimate`]: Read information of all Estimates - `mission_control.estimates.w` [`Estimate`]: Create or update all kinds of Estimates - `mission_control.lists.r` [`List`]: Read information of all List objects - `mission_control.lists.r` [`List`]: Create or update List objects - `mission_control.orders.r` [`Order`]: Read information of all orders - `mission_control.orders.w` [`Order`]: Create or update new orders - `mission_control.jobs.r` [`Job`]: Read basic information of all jobs currently or formerly in production (`GET /jobs/_*`) - `mission_control.jobs.w` [`Job`]: Create or update new jobs (`POST /jobs/_*`, `PATCH /jobs/_*`) 
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MissionControl);
  }
}(this, function(expect, MissionControl) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IntermediateProduct', function() {
      beforeEach(function() {
        instance = new MissionControl.IntermediateProduct();
      });

      it('should create an instance of IntermediateProduct', function() {
        // TODO: update the code to test IntermediateProduct
        expect(instance).to.be.a(MissionControl.IntermediateProduct);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property kind (base name: "kind")', function() {
        // TODO: update the code to test the property kind
        expect(instance).to.have.property('kind');
        // expect(instance.kind).to.be(expectedValueLiteral);
      });

      it('should have the property expectedQuantity (base name: "expected_quantity")', function() {
        // TODO: update the code to test the property expectedQuantity
        expect(instance).to.have.property('expectedQuantity');
        // expect(instance.expectedQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property actualQuantity (base name: "actual_quantity")', function() {
        // TODO: update the code to test the property actualQuantity
        expect(instance).to.have.property('actualQuantity');
        // expect(instance.actualQuantity).to.be(expectedValueLiteral);
      });

      it('should have the property completionPercentage (base name: "completion_percentage")', function() {
        // TODO: update the code to test the property completionPercentage
        expect(instance).to.have.property('completionPercentage');
        // expect(instance.completionPercentage).to.be(expectedValueLiteral);
      });

      it('should have the property consumptionPercentage (base name: "consumption_percentage")', function() {
        // TODO: update the code to test the property consumptionPercentage
        expect(instance).to.have.property('consumptionPercentage');
        // expect(instance.consumptionPercentage).to.be(expectedValueLiteral);
      });

      it('should have the property suspiciousQuantities (base name: "suspicious_quantities")', function() {
        // TODO: update the code to test the property suspiciousQuantities
        expect(instance).to.have.property('suspiciousQuantities');
        // expect(instance.suspiciousQuantities).to.be(expectedValueLiteral);
      });

      it('should have the property expectedWaste (base name: "expected_waste")', function() {
        // TODO: update the code to test the property expectedWaste
        expect(instance).to.have.property('expectedWaste');
        // expect(instance.expectedWaste).to.be(expectedValueLiteral);
      });

      it('should have the property actualWaste (base name: "actual_waste")', function() {
        // TODO: update the code to test the property actualWaste
        expect(instance).to.have.property('actualWaste');
        // expect(instance.actualWaste).to.be(expectedValueLiteral);
      });

      it('should have the property jobId (base name: "job_id")', function() {
        // TODO: update the code to test the property jobId
        expect(instance).to.have.property('jobId');
        // expect(instance.jobId).to.be(expectedValueLiteral);
      });

      it('should have the property creatingWorkstepId (base name: "creating_workstep_id")', function() {
        // TODO: update the code to test the property creatingWorkstepId
        expect(instance).to.have.property('creatingWorkstepId');
        // expect(instance.creatingWorkstepId).to.be(expectedValueLiteral);
      });

      it('should have the property consumingWorkstepId (base name: "consuming_workstep_id")', function() {
        // TODO: update the code to test the property consumingWorkstepId
        expect(instance).to.have.property('consumingWorkstepId');
        // expect(instance.consumingWorkstepId).to.be(expectedValueLiteral);
      });

      it('should have the property layout (base name: "layout")', function() {
        // TODO: update the code to test the property layout
        expect(instance).to.have.property('layout');
        // expect(instance.layout).to.be(expectedValueLiteral);
      });

    });
  });

}));
